#! /usr/bin/env python

from automatool import Automaton

print("Loading automaton...")
a = Automaton.read_csv("automatool/examples/automaton/a.csv")

print("  Set of states, X...:", a.X())
print("  Marked states, Xm..:", a.Xm())
print("  Set of events, E...:", a.E())
print("  Arcs...............:", a.count_arcs())
print("  Writing to 01_original.dot...")
a.write_dot("01_original.dot")

print("Calculate accesssible part...")
b = a.Ac()
print("  Set of states, X...:", b.X())
print("  Set of events, E...:", b.E())
print("  Arcs...............:", b.count_arcs())
print("  Writing to 02_accessible.dot...")
b.write_dot("02_accessible.dot")

print("Calculate co-accesssible part...")
b = a.CoAc()
print("  Set of states, X...:", b.X())
print("  Set of events, E...:", b.E())
print("  Arcs...............:", b.count_arcs())
print("  Writing to 03_coaccessible.dot...")
b.write_dot("03_coaccessible.dot")

print("Calculate trim part...")
b = a.trim()
print("  Set of states, X...:", b.X())
print("  Set of events, E...:", b.E())
print("  Arcs...............:", b.count_arcs())
print("  Writing to 04_trim.dot...")
b.write_dot("04_trim.dot")

print("Removing event e2...")
b = a.remove_events(['e2'])
print("  Is deterministic...:", b.is_deterministic())
print("  Set of states, X...:", b.X())
print("  Set of events, E...:", b.E())
print("  Arcs...............:", b.count_arcs())
print("  Writing to 05_non_deterministic.dot...")
b.write_dot("05_non_deterministic.dot")

print("Calculate deterministic equivalent...")
c = b.deterministic_equivalent()
print("  Is deterministic...:", c.is_deterministic())
print("  Set of states, X...:", c.X())
print("  Set of events, E...:", c.E())
print("  Arcs...............:", c.count_arcs())
print("  Write to 06_deterministic_equivalent.dot...")
c.write_dot("06_deterministic_equivalent.dot")
